version = "1.0"

[metadata]
author_name = "Bingran You"
author_email = "bingran.you@berkeley.edu"
difficulty = "medium"
category = "deep-research"
tags = ["web-search", "deep-research"]

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 400.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 4096
storage_mb = 10240
allow_internet = true

[agent.env]
EXA_API_KEY="${EXA_API_KEY}"
