// PROTOTYPE 02 — pixel art for the Explorer window, drawn as character maps.
// One character is one pixel; "." is transparent. <PixelIcon /> turns each map
// into an inline SVG with one path per colour.

export type PixelArt = {
  rows: readonly string[];
  palette: Readonly<Record<string, string>>;
};

const ink = {
  k: "#000000",
  g: "#808080",
  s: "#c0c0c0",
  w: "#ffffff",
  n: "#000080",
  t: "#008080",
  c: "#7fd4d4",
  o: "#7a5c00",
  y: "#ffd75e",
  L: "#fff3b0",
  Y: "#e3ac2f",
  b: "#1c6fd0",
  G: "#2f9e4a",
  r: "#c8321e",
  d: "#404040",
};

/** Follows the text colour, so glyphs invert with a navy selection. */
const mono = { k: "currentColor", w: "#ffffff", g: "#808080" };

export const icons = {
  folder: {
    palette: ink,
    rows: [
      "................",
      "................",
      "..ooooo.........",
      ".oLLLLLo........",
      "oLyyyyyLoooooo..",
      "oLyyyyyyLLLLLLok",
      "oLyyyyyyyyyyyyok",
      "oLyyyyyyyyyyyyok",
      "oLyyyyyyyyyyyyok",
      "oLyyyyyyyyyyyyok",
      "oLyyyyyyyyyyyyok",
      "oLyyyyyyyyyyyyok",
      "oLyyyyyyyyyyyyok",
      "oooooooooooooook",
      ".kkkkkkkkkkkkkkk",
      "................",
    ],
  },
  folderOpen: {
    palette: ink,
    rows: [
      "................",
      "................",
      "..ooooo.........",
      ".oLLLLLo........",
      "oLYYYYYLooooo...",
      "oLYYYYYYYYYYo...",
      "oLYooooooooooooo",
      "oLoLLLLLLLLLLLLo",
      "oYoLyyyyyyyyyyok",
      "ooLyyyyyyyyyyyok",
      "ooLyyyyyyyyyyok.",
      "oLyyyyyyyyyyyok.",
      "oLyyyyyyyyyyok..",
      "oooooooooooook..",
      ".kkkkkkkkkkkk...",
      "................",
    ],
  },
  document: {
    palette: ink,
    rows: [
      "................",
      "..gggggggg......",
      "..gwwwwwwgk.....",
      "..gwwwwwwgwk....",
      "..gwwwwwwgggk...",
      "..gwwwwwwwwwk...",
      "..gwnnnnnnwwk...",
      "..gwwwwwwwwwk...",
      "..gwnnnnnnnwk...",
      "..gwwwwwwwwwk...",
      "..gwnnnnnnnwk...",
      "..gwwwwwwwwwk...",
      "..gwnnnnnwwwk...",
      "..gwwwwwwwwwk...",
      "..kkkkkkkkkkk...",
      "................",
    ],
  },
  globe: {
    palette: ink,
    rows: [
      ".....kkkkkk.....",
      "...kkbbGGbbkk...",
      "..kbcbGGGGbbbk..",
      ".kbcbGGGGGbbGbk.",
      ".kbbGGGGGbbGGGk.",
      "kbbbGGGGbbbGGGGk",
      "kbbbbGGGbbbbGGGk",
      "kbbbbbGGbbbbbGbk",
      "kbbbbbGGGbbbbbbk",
      "kbbbbGGGGGbbbbbk",
      "kbbbbGGGGGGbbbbk",
      ".kbbbbGGGGGbbbk.",
      ".kbbbbbGGGbbbbk.",
      "..kbbbbbGGbbbk..",
      "...kkbbbGbbkk...",
      ".....kkkkkk.....",
    ],
  },
  house: {
    palette: ink,
    rows: [
      "................",
      ".......kk.......",
      "......krrk......",
      ".....krrrrk.....",
      "....krrrrrrk....",
      "...krrrrrrrrk...",
      "..krrrrrrrrrrk..",
      ".krrrrrrrrrrrrk.",
      "kkkkkkkkkkkkkkkk",
      "..kwwwwwwwwwwk..",
      "..kwwwwwwnnnwk..",
      "..kwkkkwwncnwk..",
      "..kwkykwwnnnwk..",
      "..kwkykwwwwwwk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  computer: {
    palette: ink,
    rows: [
      "................",
      ".kkkkkkkkkkkkk..",
      ".kwwwwwwwwwwwk..",
      ".kwtttttttttgk..",
      ".kwtccttttttgk..",
      ".kwtctttttttgk..",
      ".kwtttttttttgk..",
      ".kwtttttttttgk..",
      ".kwtttttttttgk..",
      ".ksggggggggggk..",
      ".kkkkkkkkkkkkk..",
      "....kssssssk....",
      "kkkkkkkkkkkkkkk.",
      "kwsssssskkkksGk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  atom: {
    palette: ink,
    rows: [
      "................",
      "....nn....nn....",
      "...n..nnnn..n...",
      "...n...nn...n...",
      "...n..n..n..n...",
      "...nnnnnnnnnn...",
      ".nn.nn....nn.nn.",
      "n...nn.rr.nn...n",
      "n...nn.rr.nn...n",
      ".nn.nn....nn.nn.",
      "...nnnnnnnnnn...",
      "...n..n..n..n...",
      "...n...nn...n...",
      "...n..nnnn..n...",
      "....nn....nn....",
      "................",
    ],
  },
  cap: {
    palette: ink,
    rows: [
      "................",
      "................",
      ".......kk.......",
      ".....kkddkk.....",
      "...kkddddddkk...",
      ".kkddddddddddkk.",
      "kddddddddddddddk",
      ".kkddddddddddkkY",
      "...kkddddddkk..Y",
      "...kwkkddkksk..Y",
      "...kwssddsssk..Y",
      "...kwsssssssk.YY",
      "....kkkkkkkk..YY",
      "................",
      "................",
      "................",
    ],
  },
  /* Four plain tiles in the page's own colours — deliberately not a flag. */
  start: {
    palette: ink,
    rows: [
      "................",
      ".nnnnnn..tttttt.",
      ".nnnnnn..tttttt.",
      ".nnnnnn..tttttt.",
      ".nnnnnn..tttttt.",
      ".nnnnnn..tttttt.",
      ".nnnnnn..tttttt.",
      "................",
      "................",
      ".tttttt..yyyyyy.",
      ".tttttt..yyyyyy.",
      ".tttttt..yyyyyy.",
      ".tttttt..yyyyyy.",
      ".tttttt..yyyyyy.",
      ".tttttt..yyyyyy.",
      "................",
    ],
  },
} satisfies Record<string, PixelArt>;

export const glyphs = {
  minimize: {
    palette: mono,
    rows: ["kkkkkk", "kkkkkk"],
  },
  maximize: {
    palette: mono,
    rows: [
      "kkkkkkkkk",
      "kkkkkkkkk",
      "k.......k",
      "k.......k",
      "k.......k",
      "k.......k",
      "k.......k",
      "k.......k",
      "kkkkkkkkk",
    ],
  },
  close: {
    palette: mono,
    rows: [
      "kk....kk",
      ".kk..kk.",
      "..kkkk..",
      "...kk...",
      "..kkkk..",
      ".kk..kk.",
      "kk....kk",
    ],
  },
  dropdown: {
    palette: mono,
    rows: ["kkkkkkk", ".kkkkk.", "..kkk..", "...k..."],
  },
  /** The cascading-menu arrow: "there is more behind this". */
  more: {
    palette: mono,
    rows: ["k...", "kk..", "kkk.", "kkkk", "kkk.", "kk..", "k..."],
  },
  external: {
    palette: mono,
    rows: [
      "..kkkkk",
      "....kkk",
      "...kkkk",
      "..kkk.k",
      ".kkk..k",
      "kkk....",
      "kk.....",
    ],
  },
  grip: {
    palette: mono,
    rows: [
      "...........w",
      "..........wg",
      ".........wgg",
      "........wgg.",
      ".......wgg.w",
      "......wgg.wg",
      ".....wgg.wgg",
      "....wgg.wgg.",
      "...wgg.wgg.w",
      "..wgg.wgg.wg",
      ".wgg.wgg.wgg",
      "wgg.wgg.wgg.",
    ],
  },
} satisfies Record<string, PixelArt>;
